name: Homes
main: fr.aphaistos.homes.HomesPlugin
author: Aphaistos
version: 1.0
api-version: 1.21
commands:
  home:
    description: Home Plugin main command
  sethome:
    description: Set a player's home location